services:
  prometheus:
    image: prom/prometheus
    command : 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000

volumes :
  prometheus_data : 